import type {
  Repository,
  Pipeline,
  AIAgent,
  AIModel,
  DashboardStats,
} from "./types";

export const mockStats: DashboardStats = {
  totalRepos: 24,
  activePipelines: 7,
  deployedAgents: 5,
  availableModels: 8,
};

export const mockRepos: Repository[] = [
  {
    id: "1",
    name: "neural-architect",
    fullName: "TroyLorents/neural-architect",
    description: "AI-powered DevOps dashboard with multi-provider integrations",
    language: "TypeScript",
    languages: { TypeScript: 62, CSS: 20, JavaScript: 12, HTML: 6 },
    starCount: 12,
    forkCount: 3,
    openIssues: 4,
    updatedAt: "2025-03-11T18:30:00Z",
    url: "https://github.com/TroyLorents/neural-architect",
    isPrivate: false,
    defaultBranch: "main",
    commitActivity: [2, 5, 3, 7, 5, 12, 8, 4, 9, 6, 11, 3],
    provider: "github",
  },
  {
    id: "2",
    name: "resume-match-ai",
    fullName: "TroyLorents/resume-match-ai",
    description:
      "Resume matching with Azure AI Search, semantic ranking, and gap analysis",
    language: "Python",
    languages: { Python: 48, JavaScript: 35, CSS: 12, HTML: 5 },
    starCount: 8,
    forkCount: 1,
    openIssues: 2,
    updatedAt: "2025-03-10T14:20:00Z",
    url: "https://github.com/TroyLorents/resume-match-ai",
    isPrivate: false,
    defaultBranch: "main",
    commitActivity: [0, 1, 4, 2, 6, 3, 5, 2, 4, 1, 3, 2],
    provider: "github",
  },
  {
    id: "3",
    name: "MyStudentApi",
    fullName: "TroyLorents/MyStudentApi",
    description:
      "ASP.NET Core 8 Web API for Student Hiring System with EF Core and SQL Server",
    language: "C#",
    languages: { "C#": 85, SQL: 10, JSON: 5 },
    starCount: 5,
    forkCount: 0,
    openIssues: 1,
    updatedAt: "2025-03-08T10:15:00Z",
    url: "https://github.com/TroyJLorents-GH/MyStudentApi",
    isPrivate: false,
    defaultBranch: "main",
    commitActivity: [1, 0, 2, 1, 3, 0, 1, 4, 2, 0, 3, 1],
    provider: "github",
  },
  {
    id: "4",
    name: "agent-demo",
    fullName: "TroyLorents/agent-demo",
    description: "Demo widget for Azure Foundry agents with embedded chat",
    language: "JavaScript",
    languages: { JavaScript: 55, CSS: 30, HTML: 15 },
    starCount: 3,
    forkCount: 0,
    openIssues: 0,
    updatedAt: "2025-03-05T09:45:00Z",
    url: "https://github.com/TroyLorents/agent-demo",
    isPrivate: false,
    defaultBranch: "main",
    commitActivity: [0, 2, 0, 1, 0, 3, 1, 0, 2, 1, 0, 1],
    provider: "github",
  },
  {
    id: "5",
    name: "job-advisor",
    fullName: "TroyLorents/job-advisor",
    description:
      "Resume and job advising app using Azure Foundry ResumeAgent",
    language: "JavaScript",
    languages: { JavaScript: 60, CSS: 25, HTML: 15 },
    starCount: 2,
    forkCount: 0,
    openIssues: 1,
    updatedAt: "2025-03-03T16:00:00Z",
    url: "https://github.com/TroyLorents/job-advisor",
    isPrivate: false,
    defaultBranch: "main",
    commitActivity: [1, 0, 1, 0, 2, 1, 0, 1, 0, 2, 0, 1],
    provider: "github",
  },
  {
    id: "6",
    name: "doc-intelligence-api",
    fullName: "TroyLorents/doc-intelligence-api",
    description:
      "Flask API for document analysis, job matching, and semantic search on Azure VM",
    language: "Python",
    languages: { Python: 90, Shell: 8, Dockerfile: 2 },
    starCount: 1,
    forkCount: 0,
    openIssues: 0,
    updatedAt: "2025-02-28T12:30:00Z",
    url: "https://github.com/TroyLorents/doc-intelligence-api",
    isPrivate: true,
    defaultBranch: "main",
    commitActivity: [0, 1, 0, 3, 2, 0, 0, 1, 1, 0, 2, 0],
    provider: "github",
  },
];

export const mockPipelines: Pipeline[] = [
  {
    id: "1",
    name: "Build & Deploy",
    repoName: "neural-architect",
    status: "success",
    branch: "main",
    duration: 142,
    triggeredAt: "2025-03-11T18:30:00Z",
    provider: "github",
  },
  {
    id: "2",
    name: "CI Tests",
    repoName: "resume-match-ai",
    status: "running",
    branch: "feature/search-v2",
    duration: 67,
    triggeredAt: "2025-03-11T17:45:00Z",
    provider: "github",
  },
  {
    id: "3",
    name: "Build & Deploy",
    repoName: "MyStudentApi",
    status: "success",
    branch: "main",
    duration: 98,
    triggeredAt: "2025-03-10T14:20:00Z",
    provider: "github",
  },
  {
    id: "4",
    name: "Lint & Type Check",
    repoName: "agent-demo",
    status: "failure",
    branch: "dev",
    duration: 34,
    triggeredAt: "2025-03-10T11:00:00Z",
    provider: "github",
  },
  {
    id: "5",
    name: "Deploy to Azure",
    repoName: "doc-intelligence-api",
    status: "success",
    branch: "main",
    duration: 215,
    triggeredAt: "2025-03-09T08:15:00Z",
    provider: "github",
  },
];

export const mockAgents: AIAgent[] = [
  {
    id: "1",
    name: "PersonalAssistant",
    type: "assistant",
    provider: "azure-foundry",
    status: "active",
    description: "General assistant with Cosmos DB, Web Search, and Memory Store tools",
    lastInvocation: "2025-03-11T16:00:00Z",
    invocationCount: 342,
  },
  {
    id: "2",
    name: "ResumeAgent",
    type: "data",
    provider: "azure-foundry",
    status: "active",
    description: "Job advisor that recommends which of 4 resumes to use for a given role",
    lastInvocation: "2025-03-10T14:30:00Z",
    invocationCount: 128,
  },
  {
    id: "3",
    name: "ResumeMatcherAgent",
    type: "workflow",
    provider: "azure-foundry",
    status: "active",
    description: "Receives search results from PersonalAssistant and ranks candidates",
    lastInvocation: "2025-03-09T12:00:00Z",
    invocationCount: 56,
  },
  {
    id: "4",
    name: "Code Assistant",
    type: "code",
    provider: "anthropic",
    status: "active",
    description: "Claude-powered code generation and review assistant",
    lastInvocation: "2025-03-11T18:00:00Z",
    invocationCount: 1024,
  },
  {
    id: "5",
    name: "Data Pipeline Agent",
    type: "workflow",
    provider: "azure-foundry",
    status: "inactive",
    description: "Automates ETL workflows and data transformation tasks",
    lastInvocation: "2025-02-20T09:00:00Z",
    invocationCount: 15,
  },
];

export const mockModels: AIModel[] = [
  {
    id: "1",
    name: "GPT-5.2",
    provider: "OpenAI",
    capabilities: ["chat", "code", "analysis", "vision"],
    description: "OpenAI's most advanced model with enhanced reasoning",
  },
  {
    id: "2",
    name: "Claude Opus 4.6",
    provider: "Anthropic",
    capabilities: ["chat", "code", "analysis"],
    description: "Anthropic's flagship model with 1M context window",
  },
  {
    id: "3",
    name: "Gemini 3 Flash",
    provider: "Google",
    capabilities: ["chat", "code", "vision"],
    description: "Google's fast multimodal model",
  },
  {
    id: "4",
    name: "Gemini 3 Pro",
    provider: "Google",
    capabilities: ["chat", "code", "vision", "analysis"],
    description: "Google's most capable reasoning model",
  },
  {
    id: "5",
    name: "GPT-4o",
    provider: "Azure",
    capabilities: ["chat", "code", "vision"],
    description: "Azure OpenAI deployment for production workloads",
  },
  {
    id: "6",
    name: "Llama 4 70B",
    provider: "Meta",
    capabilities: ["chat", "code"],
    description: "Open-source model for self-hosted inference",
  },
  {
    id: "7",
    name: "Mistral Large 3",
    provider: "Mistral",
    capabilities: ["chat", "code", "analysis"],
    description: "European frontier model with strong multilingual support",
  },
  {
    id: "8",
    name: "GPT-4o-mini",
    provider: "Azure",
    capabilities: ["chat", "code"],
    description: "Cost-efficient Azure deployment for high-volume tasks",
  },
];
